name: Deploy production

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          script: cd defifarms-frontend-app && git pull origin develop && yarn && yarn build

HOST:51.79.145.213
USERNAME:debian
PORT:22
PASSWORD:defifarm@2021